services:
  - type: web
    name: ts-library
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
